### ISSUE TITLE
Id "projetos"

### ISSUE THREAD

**Issue by AndersonMarquess** [Leocardoso94/leocardoso94.github.io#1]
Notei que a âncora da **nav** está apontando para _"projects"_, mas o id da seção de projetos está como _"projetos"_, dai ao clicarmos ele não leva até a seção esperada.

Achei bem maneiro seu site, parabéns.

**Comment by Leocardoso94** [comment]
Fala cara, putz verdade rsrs, obrigado pelo toque nem tinha percebido! 
Preciso dar uma atualizada nesse site rs
